apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: app
spec:
  containers:
  - name: debug
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    envFrom:
    - secretRef:
        name: minio-creds
  restartPolicy: Never

